### ISSUE TITLE
RQ 1 Script Issue

### ISSUE THREAD

**Issue by wx930910** [RedRoach51/MockResearch#5]
What does it mean by **Place all the scripts from the repository inside one directory**? Which files do we want to include here?

Also we want to mention that what are the enviornments (OS, Python Version) for running the script since .bat files only work for Windows, it is hard to run .bat files on linux as setting up the Path for Wine on linux is complex.

**Comment by RedRoach51** [comment]
Batch/Python scripts from "Erick Scripts" should be placed in the same directory as the Apache Github repositories. README.md has been updated to fix unclear instructions. 

Issue regarding special character errors in CSVReader.py has been fixed.
